name: ArgoCD CLI
description: Github Action to install ArgoCD CLI
author: Coding Protocols <support@codingprotocols.com>
branding:
  icon: 'terminal'
  color: 'gray-dark'
inputs:
  version:
    description: Version of the ArgoCD CLI to use
    required: false
    default: latest
runs:
  using: composite
  steps:
  - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    shell: bash
  - name: Configure ArgoCD CLI
    run: setup.sh
    shell: bash
    env:
      VERSION: ${{ inputs.version }}